[syntax]
level = "Lua52"

[indent]
kind = "Space"
width = 2

[layout]
max_line_width = 160
max_blank_lines = 1
table_expand = "Auto"
call_args_expand = "Auto"
func_params_expand = "Auto"
prefer_call_args_layout_from_source = true
prefer_table_layout_from_source = true
prefer_chain_break_on_statement_tail = false
prefer_binary_chain_operand_per_line = false

[output]
insert_final_newline = true
trailing_comma = "Never"
trailing_table_separator = "Multiline"
quote_style = "Preserve"
single_arg_call_parens = "Always"
simple_lambda_single_line = "Preserve"
end_of_line = "LF"

[comments]
align_line_comments = false
align_in_statements = false
align_in_table_fields = true
align_in_call_args = true
align_in_params = true
align_across_standalone_comments = false
align_same_kind_only = false
space_after_comment_dash = true
line_comment_min_spaces_before = 1
line_comment_min_column = 0

[emmy_doc]
align_tag_columns = true
align_declaration_tags = true
align_reference_tags = true
align_multiline_alias_descriptions = true
space_between_tag_columns = true
space_after_description_dash = true
compact_type_or = true

[align]
continuous_assign_statement = false
table_field = true
