data:extend({
  {
    type = "animation",
    name = "mks-dsl-lab-overlay" --[[$LAB_OVERLAY_ANIMATION_NAME]],
    filename = "__disco-science-lite__/graphics/factorio/lab-overlay.png" --[[$LAB_OVERLAY_GRAPHIC_FILE_NAME]],
    blend_mode = "additive",
    draw_as_glow = true,
    width = 216,
    height = 194,
    frame_count = 33,
    line_length = 11,
    animation_speed = 1 / 3,
    scale = 0.5,
  },
  {
    type = "animation",
    name = "mks-dsl-biolab-overlay" --[[$BIOLAB_OVERLAY_ANIMATION_NAME]],
    filename = "__disco-science-lite__/graphics/factorio/biolab-overlay.png" --[[$BIOLAB_OVERLAY_GRAPHIC_FILE_NAME]],
    blend_mode = "additive",
    draw_as_glow = true,
    width = 326,
    height = 362,
    frame_count = 32,
    line_length = 8,
    animation_speed = 1 / 3,
    scale = 0.5,
    shift = { 1 / 32, -6.5 / 32 },
  },
  {
    type = "animation",
    name = "mks-dsl-general-overlay" --[[$GENERAL_OVERLAY_ANIMATION_NAME]],
    filename = "__disco-science-lite__/graphics/general-overlay.png" --[[$GENERAL_OVERLAY_GRAPHIC_FILE_NAME]],
    blend_mode = "additive",
    draw_as_glow = true,
    width = 128,
    height = 128,
    frame_count = 33,
    line_length = 11,
    animation_speed = 1 / 3,
    scale = 0.5,
  },
})
